on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # TODO: Test a real graph
      - name: Run github action
        uses: logseq/rdf-export@main
